# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  aws-ecs: circleci/aws-ecs@2.1.0
  aws-cli: circleci/aws-cli@1.4.1
# Orchestrate or schedule a set of jobs
workflows:
  deploy:
    jobs:
      - update-tag

jobs: 
  update-tag:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - run:
          command: |
            echo 'export APP_NAME=crowdcomms' >> $BASH_ENV
            echo 'export WORKSPACE=dev' >> $BASH_ENV
            echo 'export MODULE_NAME=api' >> $BASH_ENV
            source $BASH_ENV
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - aws-ecs/update-service:
          cluster-name: '${APP_NAME}-${WORKSPACE}'
          container-image-name-updates: 'container=${APP_NAME}_${MODULE_NAME},tag=${CIRCLE_SHA1}'
          family: '${WORKSPACE}-${MODULE_NAME}'
          service-name: '${APP_NAME}-${WORKSPACE}-${MODULE_NAME}'







